### ISSUE TITLE
A mistake in 0x59_应用数学 离散数学1数理逻辑

### ISSUE THREAD

**Issue by Nagi-ovo** [guofei9987/guofei9987.github.io#17]
您好，我在学习时发现您的博客[运算律](https://www.guofei.site/2021/08/07/discrete_mathematics.html#%E8%BF%90%E7%AE%97%E5%BE%8B)中有这样一个问题：

8.同一律和零律 第二条  P∧F⇔P
此处应为P∧T ⇔ P

**Comment by guofei9987** [comment]
感谢！已改正
